global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: cluster-data-center-1

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ["localhost:9090"]
